name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub using CLI
        run: docker login -u ${{ secrets.DOCKER_HUB_TOKEN }} -p ${{ secrets.DOCKER_HUB_TOKEN_PASS }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_TOKEN }}/deutsche-springboot-demo:latest .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_TOKEN }}/deutsche-springboot-demo:latest
